set_input_delay -max 1 [get_ports "J"] 
set_input_delay -max 1 [get_ports "K"] 
set_input_delay -max 1 [get_ports "en"] 
set_output_delay -max 1 [get_ports "Q"] 
set_output_delay -max 1 [get_ports "Qm"]